collection @featured_projects
attributes 	:address, 
			:address2, 
			:city, 
			:country,
			:event_end_time, 
			:event_start_time,
			:fundraiser_type_id,
			:host,
			:id, 
			:lat,
			:lng,
			:long_description,
			:name,
			:project_id,
			:public,
			:short_description,
			:users_attending, 
			:users_maybe_attending, 
			:users_not_attending, 
			:users_with_no_response, 
			:state, 
			:zip	